eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true

microservice:
  microservicePayment:
    endpoints:
      endpoint:
        uri: http://MICROSERVICEPAYMENT/payment/doPayment
    microserviceBooking:
      endpoints:
        endpoint:
          uri: http://MICROSERVICEBOOKING/book/bookOrder
